[package]
name = "vxl_3"
version = "0.1.0"
authors = ["Pavel Volkov <pvolkov@delimobil.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
